# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'universalapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for universalapp
  pod 'AppCenter/Analytics', '~> 1.4.0'
  pod 'AppCenterReactNativeShared', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'universalappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'universalapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for universalapp-tvOS

  target 'universalapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
